#!/bin/bash
set +x
set -e

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS_DIR=${SCRIPTS_DIR:-$BASE_DIR/.scripts}
HOST=`hostname -s`
BACKUP_DIR=${BACKUP_DIR:-$BASE_DIR/.backup}; mkdir -p $BACKUP_DIR

source "$BASE_DIR"/$HOST/jboss.conf
source "$SCRIPTS_DIR"/jboss.conf

if ! grep -q $JBOSS_GROUP /etc/group
then
   echo "Criando o grupo $JBOSS_GROUP ..."
   sudo groupadd $JBOSS_GROUP
fi

if ! grep -q $JBOSS_USER /etc/passwd
then
   echo "Criando o usuário $JBOSS_USER ..."
   sudo useradd $JBOSS_USER -g $JBOSS_GROUP -K UMASK=007
fi
