#!/bin/bash

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS=${SCRIPTS:-$BASE_DIR/.scripts}

DC_TYPE=${DC_TYPE:-primary}

$SCRIPTS/restaurar-cache-de-pacotes
$SCRIPTS/atualizar-e-instalar-pacotes
$SCRIPTS/instalar-oracle-jdk
$SCRIPTS/criar-usuario-jboss
$SCRIPTS/instalar-jboss
$SCRIPTS/iniciar-jboss
$SCRIPTS/instalar-maven
$SCRIPTS/instalar-git
$SCRIPTS/salvar-cache-de-pacotes
