#!/bin/bash
set +x
set -e

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS_DIR=${SCRIPTS_DIR:-$BASE_DIR/.scripts}
HOST=`hostname -s`
BACKUP_DIR=${BACKUP_DIR:-$BASE_DIR/.backup}; mkdir -p $BACKUP_DIR

source "$BASE_DIR"/$HOST/jboss.conf
source "$SCRIPTS_DIR"/jboss.conf

cd $JBOSS_PARENT_HOME

if grep -q $JBOSS_USER /etc/passwd
then
  echo "Matando processos do usuário $JBOSS_USER ..."
  sudo pkill -u $JBOSS_USER || true
  sleep 1

  echo "Removendo o usuário $JBOSS_USER ..."
  sudo userdel -rf $JBOSS_USER || true
fi

echo "Removendo arquivos de instalações anteriores ..."
sudo rm -rf `dirname $JBOSS_CONF` $JBOSS_INIT $JBOSS_DIR
